#!/usr/bin/env python
#
# Author: Martin Souchal 
# Date  : 20 oct 2016
# Desc. : CPU slot report for APC Cluster
#
#
#
#
import pbs
from PBSQuery import PBSQuery
from PBSQuery import PBSError
import sys

def countcpu(queue):
    p = PBSQuery()
    p.new_data_structure()
    nodes = p.getnodes("*")
    nptot = 0
    for id in nodes:
        if nodes[id].properties == [queue]:
            try:
                np = nodes[id].np
                np = int(np[0])
                nptot = nptot + np
            except PBSError, detail:
                print detail
            pass
    return nptot
    
def countppn(queue):
    p = PBSQuery()
    p.new_data_structure()
    jobs = p.getjobs()
    nptot = 0
    for id in jobs:
        try:
            if jobs[id].queue[0] == queue and jobs[id].job_state[0] == 'R':
                np = jobs[id].Resource_List.nodes
                np = np[0].split('=')
                nu = len(np)
                if nu == 1:
                    np = 1
                else:
                    np = int(np[1])
                nptot = np + nptot
        except PBSError, detail:
            print detail
        pass
    return nptot

def main():
    nptotf = countcpu('furious') 
    nptotq = countcpu('quiet')
    nptotusef = countppn('furious')
    nptotuseq = countppn('quiet')
    print "CPU cluster usage :"
    print "Quiet : [ %s / %s ]" % (nptotuseq,nptotq)
    print "Furious : [ %s / %s ]" % (nptotusef,nptotf)

main()
